numbers = [5, 10, 15]
numbers.append(20)
print(numbers)
numbers.insert(1, 7)
print(numbers)
numbers.append("Python")
print(numbers)
numbers.remove(10)
print(numbers)
numbers.pop()
b = numbers.pop()
print(numbers)
print(b)
numbers.pop(1)
print(numbers)
numbers.clear()
print(numbers)
letters = ["a", "b", "c"]
c = letters.copy()
d = list(letters)
print(c, d)
print(id(c), id(d))
marks = [2, 3, 5, 3, 4, 5, 2, 3]
print(marks.count(3))
print(marks.index(5))
if 6 in marks:
    print("Оценка 6 есть в списке")
else:
    print("Оценки 6 нет в списке")
nums = [8, 2, 5, 1, 7]
nums.sort()
print(nums)
nums.sort(reverse=True)
print(nums)
cities = ["Москва", "Тверь", "Казань", "Екатеринбург"]
cities.sort()
print(cities)
bb = sorted(cities)
print(bb, cities)
chars = list("programming")
print(chars.count("g"))
chars.reverse()
print(chars)
chars.sort()
print(chars)
print(sorted(chars))